name: AdminNotes
main: eu.mapleconsulting.adminnotes.AdminNotes
version: 1.0
api-version: 1.17
website: www.mapleconsulting.eu
commands:
  note:
    description: AdminNotes /ote command, main root command
    usage: 
           /note write <player> <note> - writes a note about player <player>
           /note seelast <player> <notes_number> - displays the last <notes_number> about <player>. If <notes_number> is not provided, all notes are shown
           /note record <moderator> - creates a file gathering all notes that have player <moderator> as author
           /note lastbyauthor <author> <notes_number> - displays the last <notes_number> that have <author> as author
           /note clean - cleans old notes and records
           /note addmail <e-mail> - adds <e-mail> to the email database
           /note sendmenote <player> - sends a notes file about <player> to your mail, if specified
           /note displaymail - displays your saved mail
           /note flagexpired - marks the old notes as expired, that will be deleted soon
           /note help - shows the help menu
           /note reload - reloads the configuration file
           /note delete <player> - deletes a note file on <player>