name: AdminNotes
main: eu.mapleconsulting.adminnotes.AdminNotes
version: 1.0
api-version: 1.17
website: www.mapleconsulting.eu
commands:
  note:
    description: AdminNotes /ote command, main root command
    usage: 
           /note write <player> <note> - writes a note about player <player>
           /note seelast <player> <notes_number> - displays the last <notes_number> about <player>. If <notes_number> is not provided, all notes are shown
           /note record <moderator> - creates a file gathering all notes that have player <moderator> as author
           /note lastbyauthor <author> <notes_number> - displays the last <notes_number> that have <author> as author
           /note clean - cleans old notes and records
           /note addmail <e-mail> - adds <e-mail> to the email database
           /note sendmenote <player> - sends a notes file about <player> to your mail, if specified
           /note displaymail - displays your saved mail
           /note flagexpired - marks the old notes as expired, that will be deleted soon
           /note help - shows the help menu
           /note reload - reloads the configuration file
           /note delete <player> - deletes a note file on <player>
           
  permissions:
    note.command.*:
        description: Player can use all /note sub-commands
        children:
            note.command.write: true
            note.command.seelast: true
            note.command.record: true
            note.command.lastbyauthor: true
            note.command.clean: true
            note.command.addmail: true
            note.command.sendmedevilnotes: true
            note.command.displaymail: true
            note.command.flagexpired: true
            note.command.reload: true
            note.command.delete: true
            note.command.notify: true
            note.command.confirm: true
            note.command.abort: true
            note.command.update: true
            note.command.flagasnotexpired: true
            note.command.help: true
    note.helpercommands.*:
        description: Commands for non-ops and non-admins
        children:
            note.command.write: true
            note.command.seelast: true
            note.command.lastbyauthor: true
            note.command.notify: true
            note.command.help: true
    note.command.write:
        description: Il giocatore puo' usare /note write
        default: op
    note.command.seelast:
        description: Il giocatore puo' usare /note seelast
        default: op
    note.command.record:
        description: Il giocatore puo' usare /note record
        default: op
    note.command.lastbyauthor:
        description: Il giocatore puo' usare /note lastbyauthor
        default: op
    note.command.clean:
        description: Il giocatore puo' usare /note clean
        default: op
    note.command.addmail:
        description: Il giocatore puo' usare /note addmail
        default: op
    note.command.sendmenote:
        description: Il giocatore puo' usare /note sendnote
        default: op
    note.command.displaymail:
        description: Il giocatore puo' usare /note sendnote
        default: op
    note.command.flagexpired:
        description: Il giocatore puo' usare /note flagexpired
        default: op
    note.command.reload:
        descriprion: Il giocatore puo' usare /note reload
        default: op
    note.command.delete:
        description: Il giocatore puo' usare /note delete
        default: op
    note.command.notify:
        description: Il giocatore e' notificato quando entra un player con piu' di n richiami
        default: op
    note.command.flagasnotexpired:
        description: Il giocatore puo' usare il comando /note flagasnotexpired
        default: op
    note.command.confirm:
        description: Il giocatore puo' usare il comando /note confirm
        default: op
    note.command.abort:
        description: Il giocatore puo' usare il comando /note abort
        default: op
    note.command.update:
        description: Al giocatore e' notificata la presenza di nuove versioni del plugin
        default: op
    note.command.help:
        description: Il giocatore puo' usare /note help
        default: op